python src/run_summarization.py \
    --model_name_or_path google/pegasus-large --tokenizer_name google/pegasus-large \
    --do_train \
    --do_eval \
    --dataset_name scientific_papers \
    --dataset_config_name pubmed \
    --task summarization \
    --max_train_samples 1000 \
    --output_dir pegasus_pubmed/models --logging_dir pegasus_pubmed/models/logs \
    --seed 100 \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --overwrite_output_dir \
    --predict_with_generate \
    --max_val_samples 500 \
    --learning_rate 1e-4 \
    --adafactor \
    --max_source_length 512 --max_target_length 128 --val_max_target_length 128 --pad_to_max_length \
    --num_beams 3 \
    --num_train_epochs 3 --save_step 100 --save_total_limit 1 \
    --load_best_model_at_end \
    --evaluation_strategy epoch --metric_for_best_model rouge2 --greater_is_better true
